package com.infobite.stygian.activity;

import android.os.Build;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.text.Html;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;

import com.infobite.stygian.R;

public class PolicyActivity extends AppCompatActivity {

    ImageView backBtn;
    TextView tvPolicy;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_policy);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        backBtn = findViewById(R.id.imgBack);
        tvPolicy = (TextView) findViewById(R.id.tvPolicy);
        backBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                finish();
            }
        });

        init();
    }

    private void init() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            tvPolicy.setText(Html.fromHtml("<p><span style=\"font-size: 13pt;\"><strong>TERMS &amp; CONDITIONS</strong></span></p>\n" +
                    "<p>PLEASE READ THIS TERMS &amp; CONDITIONS OF USE OF WWW.STYGIAN.COM<br />CAREFULLY. BY USING THIS WEBSITE OR ORDERING PRODUCTS FROM THIS<br />WEBSITE YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS<br />OF THIS DOCUMENT.<br />These Terms &amp; Conditions (herein after referred to as the \"Terms\") governs<br />your use of this website www.stygianstore.com (herein after referred to as the<br />\"Website\"), offer of products for purchase on this Website, or your purchase<br />of products available on this Website. These terms includes, and incorporates<br />by this reference, the policies and guidelines referenced below. The website<br />reserves the right to change or revise the terms and conditions of use of this<br />website at any time by posting any changes or a revised terms on this Website.<br />The website will alert you about the changes or revisions which have been<br />made by indicating on the top of the revised Terms and Conditions the date it<br />was last revised. The changed or revised terms will be effective immediately<br />after it is posted on this Website. Your use of the Website following the posting<br />of any such changes or of a revised terms will constitute your acceptance of<br />any such changes or revisions. Stygian Store (&ldquo;The Business name&rdquo;)<br />encourages you to review these terms whenever you visit the Website to make<br />sure that you understand the terms and conditions governing use of the<br />Website. These terms does not alter in any way the terms or conditions of any<br />other written agreement you may have with stygian Store for other products<br />or services. If you do not agree to this Agreement (including any referenced<br />policies or guidelines), please immediately terminate your use of the Website.<br />These Terms apply in full force and effect to your use of this Website and by<br />using this Website, you expressly accept all terms and conditions contained<br />herein in full.</p>\n" +
                    "<p><br /><strong>I. PRODUCTS</strong></p>\n" +
                    "<p>Terms of Offer: This Website offers for sale certain products (the \"Products\").<br />By placing an order for Products through this Website, you agree to the terms<br />set forth in these terms and conditions contained herein in full along with<br />conditions mentioned in the product display page on the website. The terms<br />mentioned in the Product page will be applicable in case of anything contrary<br />mentioned in the Website Terms &amp; Conditions and Return &amp; Refund Policy of<br />the website.<br />Opt Out Procedure: You may use UNSUBSCRIBE link found in any email<br />solicitation that you may receive.<br />Proprietary Rights: The business has proprietary rights over all products<br />available on the website. You may not copy, reproduce, resell or redistribute<br />any Product manufactured and/or distributed by www.stygianstore.com<br />including all trademarks and specific layouts of this webpage, including calls to<br />action, text placement, images and other information.</p>\n" +
                    "<p><br /><strong>II. WEBSITE</strong></p>\n" +
                    "<p>Content, Intellectual Property &amp; Third Party Links: In addition to making<br />Products available, this Website also offers information and marketing<br />materials. We does not always create the information offered on this Website;<br />instead the information is often gathered from other sources. To the extent<br />that the business does create the content on this Website, such content is<br />protected by intellectual property laws of the India, foreign nations, and<br />international bodies. Unauthorized use of the material may violate copyright,<br />trademark, and/or other laws. You acknowledge that your use of the content<br />on this Website is for personal, non-commercial use. Any links to third-party<br />websites are provided solely as a convenience to you. The business does not<br />endorse the contents on any such third-party websites and is not responsible<br />for the content of or any damage that may result from your access to or</p>\n" +
                    "<p>reliance on these third-party websites. If you link to third-party websites, you<br />do so at your own risk.<br />Use of Website: We are not responsible for any damages resulting from use of<br />this website by anyone. You will not use the Website for illegal purposes. You<br />will (1) abide by all applicable local, state, national, and international laws and<br />regulations in your use of the Website (including laws regarding intellectual<br />property), (2) no interference with or disrupt the use and enjoyment of the<br />Website by other users, (3) not to resell material on the Website, (4) not<br />engage, directly or indirectly, in transmission of \"spam\", chain letters, junk<br />mail or any other type of unsolicited communication, and (5) not defame,<br />harass, abuse, or disrupt other users of the Website</p>\n" +
                    "<p>License: By using this Website, you are granted a limited, non-exclusive, non-<br />transferable right to use the content and materials on the Website in</p>\n" +
                    "<p>connection with your normal, non-commercial use of the Website. You may not<br />copy, reproduce, transmit, distribute, or create derivative works of such<br />content or information without express written authorization from the company<br />or the applicable third party (if third party content is at issue).<br />Posting: By posting, storing, or transmitting any content on the Website, you<br />hereby grant the company a perpetual, worldwide, non-exclusive, royalty-free,<br />assignable, right and license to use, copy, display, perform, distribute, have<br />distributed, transmit and assign such content in any form, in all media now<br />known or hereinafter created, anywhere in the world. Stygianstore.com does<br />not have the ability to control the nature of the user-generated content offered<br />through the Website. You are solely responsible for your interactions with other<br />users of the Website (If any) and any content you post. The company is not<br />liable for any damage or harm resulting from any posts by or interactions<br />between users. The company reserves the right, but has no obligation, to<br />monitor interactions between and among users of the Website and to remove<br />any content which we deems objectionable.</p>\n" +
                    "<p><strong>III. DISCLAIMER OF WARRANTIES</strong></p>\n" +
                    "<p>YOUR USE OF THIS WEBSITE AND/OR PRODUCTS ARE AT YOUR OWN SOLE<br />RISK. THE WEBSITE AND PRODUCTS ARE OFFERED ON AN \"AS IS\" AND \"AS<br />AVAILABLE\" BASIS. STYGIANSTORE.COM EXPRESSLY DISCLAIMS ALL<br />WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING,<br />BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS<br />FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT WITH RESPECT TO<br />THE PRODUCTS OR WEBSITE CONTENT, OR ANY RELIANCE UPON OR USE OF<br />THE WEBSITE CONTENT OR PRODUCTS. THAT ANY WARRANY OF ANY<br />PRODUCTS BEING DEALT ON THIS WEBSITE SHALL BE CLEARLY MENTIONED<br />AGAINST THE PRODUCTS LISTED ON THE WEBSITE AND SHALL BE DEALT BY<br />THE VENDOR ITSELF WITHOUT ANY RESPONSIBILITY OF THE WEBSITE.<br />THAT THE INFORMATION PROVIDED ON THIS WEBSITE IS ACCURATE,<br />RELIABLE, COMPLETE, OR TIMELY.<br />NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY<br />YOU FROM THIS WEBSITE WILL CREATE ANY WARRANTY NOT EXPRESSLY<br />STATED HEREIN.</p>\n" +
                    "<p><strong>IV. LIMITATION OF LIABILITY</strong></p>\n" +
                    "<p>STYGIAN STORE ENTIRE LIABILITY, AND YOUR EXCLUSIVE REMEDY, IN LAW,<br />IN EQUITY, OR OTHWERWISE, WITH RESPECT TO THE WEBSITE CONTENT<br />AND PRODUCTS AND/OR FOR ANY BREACH OF THIS AGREEMENT IS SOLELY<br />LIMITED TO THE AMOUNT YOU PAID, LESS SHIPPING AND HANDLING, FOR<br />PRODUCTS PURCHASED VIA THE WEBSITE.<br />STYGIAN STORE WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT,<br />INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES IN CONNECTION WITH</p>\n" +
                    "<p>THESE TERMS OR THE PRODUCTS IN ANY MANNER, INCLUDING LIABILITIES<br />RESULTING FROM (1) THE USE OR THE INABILITY TO USE THE WEBSITE<br />CONTENT OR PRODUCTS; (2) THE COST OF PROCURING SUBSTITUTE<br />PRODUCTS OR CONTENT; (3) ANY PRODUCTS PURCHASED OR OBTAINED OR<br />TRANSACTIONS ENTERED INTO THROUGH THE WEBSITE; OR (4) ANY LOST<br />PROFITS YOU ALLEGE.<br />SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF<br />LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES SO SOME OF THE<br />ABOVE LIMITATIONS MAY NOT APPLY TO YOU.<br />V. INDEMNIFICATION</p>\n" +
                    "<p>You will release, indemnify, defend and hold harmless STYGIAN STORE, and<br />any of its contractors, agents, employees, officers, directors, shareholders,<br />affiliates and assigns from all liabilities, claims, damages, costs and expenses,<br />including reasonable attorneys' fees and expenses, of third parties relating to<br />or arising out of (1) these terms or the breach of your warranties,<br />representations and obligations under these terms; (2) the Website content or<br />your use of the Website content; (3) the Products or your use of the Products;<br />(4) any intellectual property or other proprietary right of any person or entity;<br />(5) your violation of any provision of this Agreement; or (6) any information<br />or data you supplied to the business.</p>\n" +
                    "<p><br /><strong>VI. PRIVACY</strong></p>\n" +
                    "<p>Stygian Store believes strongly in protecting user privacy and data protection.<br />Please refer to the Company&rsquo;s privacy policy mentioned on the website for<br />more details.</p>\n" +
                    "<p><strong>VI. AGREEMENT TO BE BOUND</strong></p>\n" +
                    "<p>By using this Website or ordering Products, you acknowledge that you have<br />read and agree to be bound by this Agreement and all terms and conditions<br />on this Website.</p>\n" +
                    "<p><br /><strong>VIII. GENERAL</strong></p>\n" +
                    "<p>Force Majeure: Stygian Store will not be deemed in default hereunder or held<br />responsible for any cessation, interruption or delay in the performance of its<br />obligations hereunder due to earthquake, flood, fire, storm, natural disaster,<br />act of God, war, terrorism, armed conflict, labor strike, lockout, or boycott.<br />Cessation of Operation: Stygian Store may at any time, in its sole discretion<br />and without advance notice to you, cease operation of the Website and<br />distribution of the Products.<br />Entire Agreement: These terms comprises the entire understanding between<br />you and the business and supersedes any prior terms pertaining to the subject<br />matter contained herein.<br />Effect of Waiver: The failure of Business to exercise or enforce any right or<br />provision of this Agreement will not constitute a waiver of such right or<br />provision. If any provision of this Agreement is found by a court of competent<br />jurisdiction to be invalid, the parties nevertheless agree that the court should<br />endeavor to give effect to the parties' intentions as reflected in the provision,<br />and the other provisions of this Agreement remain in full force and effect.<br />Governing Law &amp; Jurisdiction: This Website originates from the City of Bhopal<br />in the Indian State of Madhya Pradesh. These terms will be governed by the<br />laws of India. The courts of Bhopal Shall have jurisdiction in dealing with any<br />legal issue arising from these terms. By using this Website or ordering</p>\n" +
                    "<p>Products, you consent to the jurisdiction and venue of such courts in<br />connection with any action, suit, proceeding or claim arising under or by reason<br />of this Agreement.<br />Domestic Use: Stygian Store makes no representation that the Website or<br />Products are appropriate or available for use in locations outside India. Users<br />who access the Website from outside India do so at their own risk and initiative<br />and must bear all responsibility for compliance with any applicable local laws.<br />All applicable taxes shall have to borne by respective purchaser of the<br />products.</p>\n" +
                    "<p>&nbsp;</p>\n" +
                    "<p><strong><span style=\"font-size: 13pt;\">RETURN AND REFUND POLICY</span></strong></p>\n" +
                    "<p>Thank you for your purchase. We hope you are happy with your purchase. However,<br />if you are not completely satisfied with your purchase for any reason, you may return<br />it to us for a full refund or credit or an exchange only. Please see below for more<br />information on our return and refund policy.</p>\n" +
                    "<p><strong>RETURN POLICY</strong></p>\n" +
                    "<p>The following is the return policy as applicable to all items sold on<br />www.stygianstore.com.<br />1. In general, an item may be eligible for return within 7 days from the delivery date.<br />The product can be returned if it fulfils one or more of the following conditions:<br />o Was delivered in a physically damaged condition<br />o Has missing parts or accessories<br />o Is different from what was ordered<br />o Is different from its description on the product detail page on website</p>\n" +
                    "<p>Products marked as \"non-returnable\" on the product detail page cannot be<br />returned. Products which are imported or are specially requested by the customer<br />will be &ldquo;non- returnable&rdquo; unless the conditions mentioned in Clause 1 of the<br />return policy is applicable.<br />2. All items must be returned in their original condition, with price tags intact, user<br />manual, warranty cards, original accessories and in the original manufacturer&rsquo;s<br />box/packaging as delivered to you. We may reject the return pickup or reject the<br />returned item if the items are not returned according to the policy mentioned or<br />the item is not in a saleable condition.<br />3. If you wish to return an electronic device that stores any personal information,<br />please ensure that you have removed all such personal information from the</p>\n" +
                    "<p>device prior to returning. The Company or the marketplace shall not be liable in<br />any manner for any misuse or usage of such information.<br />4. In some cases, items may not be eligible for return, including cases of buyer's<br />remorse such as incorrect model or colour of product ordered or incorrect product<br />ordered.<br />5. Some of the goods available on the website may have a different return and refund<br />policy which shall be applicable only for the product where such policy is<br />specifically mentioned. In that case, this general policy will not be applicable to<br />such products or class or products.</p>\n" +
                    "<p><strong>Return Process</strong></p>\n" +
                    "<p>To return an item, initiate the return process by sending an email to the customer<br />service at __________________________ [email address] to confirm about the<br />goods to be returned. After receiving the confirmation of the return, place the item<br />securely in its original packaging and include your proof of Purchase /and the return<br />form provided (If any). A representative from the Shipping partner of the company or<br />seller will come and inspect the conditions on which the return can be executed and if<br />all the conditions are met he will take the item back and will issue the Goods Return<br />slip which shall be the proof that the goods has been returned and delivered to the<br />seller. In no case, the return shall be processed by Stygianstore.com, but we will only<br />be assisting in the whole process. The return shall be processed by the seller of the<br />product.</p>\n" +
                    "<p><strong>REFUND POLICY</strong></p>\n" +
                    "<p>In any case where a refund is required, the sellers need to authorise that refund.<br />Stygianstore.com can assist in facilitating refunds for you only when the seller notifies<br />us of the receipt of the item. Generally, the seller will process the refund within 7 days</p>\n" +
                    "<p>from the receipt of the product by the seller. Once the seller notifies us of the receipt<br />of the return item, the following timelines apply for the amount to be credited.</p>\n" +
                    "<p>Payment<br />Method</p>\n" +
                    "<p>Refund Method Refund Time-frame</p>\n" +
                    "<p>(After seller notifies Stygianstore.com<br />of receipt of return)</p>\n" +
                    "<p>Credit Card/<br />Debit Card</p>\n" +
                    "<p>Credit Card/<br />Debit Card</p>\n" +
                    "<p>3-5 Business Days</p>\n" +
                    "<p>Net Banking Net Banking<br />Account</p>\n" +
                    "<p>3-5 Business Days</p>\n" +
                    "<p>UPI UPI Linked Bank<br />Account</p>\n" +
                    "<p>2-4 Business days</p>\n" +
                    "<p>Pay on Delivery NEFT to Bank<br />Account</p>\n" +
                    "<p>3-5 Business Days</p>\n" +
                    "<p>In Rare circumstances, there may be delay in crediting of the refund amount even after<br />it being processed by the seller&rsquo;s bank. In such case, you may have to contact your</p>\n" +
                    "<p>bank for crediting the same to your account. The products which are categorized &ldquo;non-<br />returnable&rdquo;, no request for its refund or return or exchange will be taken unless the</p>\n" +
                    "<p>conditions mentioned in Clause 1 of the return policy is applicable.</p>\n" +
                    "<p>NOTE :- THE RETURN AND REFUND POLICY OF THE COMPANY IS SUBJECT TO<br />FURTHER CHANGE WITHOUT ANY FURTHER INTIMATION.</p>\n" +
                    "<p>.</p>", Html.FROM_HTML_MODE_COMPACT));
        } else {
            tvPolicy.setText(Html.fromHtml("<p><span style=\"font-size: 13pt;\"><strong>TERMS &amp; CONDITIONS</strong></span></p>\n" +
                    "<p>PLEASE READ THIS TERMS &amp; CONDITIONS OF USE OF WWW.STYGIAN.COM<br />CAREFULLY. BY USING THIS WEBSITE OR ORDERING PRODUCTS FROM THIS<br />WEBSITE YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS<br />OF THIS DOCUMENT.<br />These Terms &amp; Conditions (herein after referred to as the \"Terms\") governs<br />your use of this website www.stygianstore.com (herein after referred to as the<br />\"Website\"), offer of products for purchase on this Website, or your purchase<br />of products available on this Website. These terms includes, and incorporates<br />by this reference, the policies and guidelines referenced below. The website<br />reserves the right to change or revise the terms and conditions of use of this<br />website at any time by posting any changes or a revised terms on this Website.<br />The website will alert you about the changes or revisions which have been<br />made by indicating on the top of the revised Terms and Conditions the date it<br />was last revised. The changed or revised terms will be effective immediately<br />after it is posted on this Website. Your use of the Website following the posting<br />of any such changes or of a revised terms will constitute your acceptance of<br />any such changes or revisions. Stygian Store (&ldquo;The Business name&rdquo;)<br />encourages you to review these terms whenever you visit the Website to make<br />sure that you understand the terms and conditions governing use of the<br />Website. These terms does not alter in any way the terms or conditions of any<br />other written agreement you may have with stygian Store for other products<br />or services. If you do not agree to this Agreement (including any referenced<br />policies or guidelines), please immediately terminate your use of the Website.<br />These Terms apply in full force and effect to your use of this Website and by<br />using this Website, you expressly accept all terms and conditions contained<br />herein in full.</p>\n" +
                    "<p><br /><strong>I. PRODUCTS</strong></p>\n" +
                    "<p>Terms of Offer: This Website offers for sale certain products (the \"Products\").<br />By placing an order for Products through this Website, you agree to the terms<br />set forth in these terms and conditions contained herein in full along with<br />conditions mentioned in the product display page on the website. The terms<br />mentioned in the Product page will be applicable in case of anything contrary<br />mentioned in the Website Terms &amp; Conditions and Return &amp; Refund Policy of<br />the website.<br />Opt Out Procedure: You may use UNSUBSCRIBE link found in any email<br />solicitation that you may receive.<br />Proprietary Rights: The business has proprietary rights over all products<br />available on the website. You may not copy, reproduce, resell or redistribute<br />any Product manufactured and/or distributed by www.stygianstore.com<br />including all trademarks and specific layouts of this webpage, including calls to<br />action, text placement, images and other information.</p>\n" +
                    "<p><br /><strong>II. WEBSITE</strong></p>\n" +
                    "<p>Content, Intellectual Property &amp; Third Party Links: In addition to making<br />Products available, this Website also offers information and marketing<br />materials. We does not always create the information offered on this Website;<br />instead the information is often gathered from other sources. To the extent<br />that the business does create the content on this Website, such content is<br />protected by intellectual property laws of the India, foreign nations, and<br />international bodies. Unauthorized use of the material may violate copyright,<br />trademark, and/or other laws. You acknowledge that your use of the content<br />on this Website is for personal, non-commercial use. Any links to third-party<br />websites are provided solely as a convenience to you. The business does not<br />endorse the contents on any such third-party websites and is not responsible<br />for the content of or any damage that may result from your access to or</p>\n" +
                    "<p>reliance on these third-party websites. If you link to third-party websites, you<br />do so at your own risk.<br />Use of Website: We are not responsible for any damages resulting from use of<br />this website by anyone. You will not use the Website for illegal purposes. You<br />will (1) abide by all applicable local, state, national, and international laws and<br />regulations in your use of the Website (including laws regarding intellectual<br />property), (2) no interference with or disrupt the use and enjoyment of the<br />Website by other users, (3) not to resell material on the Website, (4) not<br />engage, directly or indirectly, in transmission of \"spam\", chain letters, junk<br />mail or any other type of unsolicited communication, and (5) not defame,<br />harass, abuse, or disrupt other users of the Website</p>\n" +
                    "<p>License: By using this Website, you are granted a limited, non-exclusive, non-<br />transferable right to use the content and materials on the Website in</p>\n" +
                    "<p>connection with your normal, non-commercial use of the Website. You may not<br />copy, reproduce, transmit, distribute, or create derivative works of such<br />content or information without express written authorization from the company<br />or the applicable third party (if third party content is at issue).<br />Posting: By posting, storing, or transmitting any content on the Website, you<br />hereby grant the company a perpetual, worldwide, non-exclusive, royalty-free,<br />assignable, right and license to use, copy, display, perform, distribute, have<br />distributed, transmit and assign such content in any form, in all media now<br />known or hereinafter created, anywhere in the world. Stygianstore.com does<br />not have the ability to control the nature of the user-generated content offered<br />through the Website. You are solely responsible for your interactions with other<br />users of the Website (If any) and any content you post. The company is not<br />liable for any damage or harm resulting from any posts by or interactions<br />between users. The company reserves the right, but has no obligation, to<br />monitor interactions between and among users of the Website and to remove<br />any content which we deems objectionable.</p>\n" +
                    "<p><strong>III. DISCLAIMER OF WARRANTIES</strong></p>\n" +
                    "<p>YOUR USE OF THIS WEBSITE AND/OR PRODUCTS ARE AT YOUR OWN SOLE<br />RISK. THE WEBSITE AND PRODUCTS ARE OFFERED ON AN \"AS IS\" AND \"AS<br />AVAILABLE\" BASIS. STYGIANSTORE.COM EXPRESSLY DISCLAIMS ALL<br />WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING,<br />BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS<br />FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT WITH RESPECT TO<br />THE PRODUCTS OR WEBSITE CONTENT, OR ANY RELIANCE UPON OR USE OF<br />THE WEBSITE CONTENT OR PRODUCTS. THAT ANY WARRANY OF ANY<br />PRODUCTS BEING DEALT ON THIS WEBSITE SHALL BE CLEARLY MENTIONED<br />AGAINST THE PRODUCTS LISTED ON THE WEBSITE AND SHALL BE DEALT BY<br />THE VENDOR ITSELF WITHOUT ANY RESPONSIBILITY OF THE WEBSITE.<br />THAT THE INFORMATION PROVIDED ON THIS WEBSITE IS ACCURATE,<br />RELIABLE, COMPLETE, OR TIMELY.<br />NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY<br />YOU FROM THIS WEBSITE WILL CREATE ANY WARRANTY NOT EXPRESSLY<br />STATED HEREIN.</p>\n" +
                    "<p><strong>IV. LIMITATION OF LIABILITY</strong></p>\n" +
                    "<p>STYGIAN STORE ENTIRE LIABILITY, AND YOUR EXCLUSIVE REMEDY, IN LAW,<br />IN EQUITY, OR OTHWERWISE, WITH RESPECT TO THE WEBSITE CONTENT<br />AND PRODUCTS AND/OR FOR ANY BREACH OF THIS AGREEMENT IS SOLELY<br />LIMITED TO THE AMOUNT YOU PAID, LESS SHIPPING AND HANDLING, FOR<br />PRODUCTS PURCHASED VIA THE WEBSITE.<br />STYGIAN STORE WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT,<br />INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES IN CONNECTION WITH</p>\n" +
                    "<p>THESE TERMS OR THE PRODUCTS IN ANY MANNER, INCLUDING LIABILITIES<br />RESULTING FROM (1) THE USE OR THE INABILITY TO USE THE WEBSITE<br />CONTENT OR PRODUCTS; (2) THE COST OF PROCURING SUBSTITUTE<br />PRODUCTS OR CONTENT; (3) ANY PRODUCTS PURCHASED OR OBTAINED OR<br />TRANSACTIONS ENTERED INTO THROUGH THE WEBSITE; OR (4) ANY LOST<br />PROFITS YOU ALLEGE.<br />SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF<br />LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES SO SOME OF THE<br />ABOVE LIMITATIONS MAY NOT APPLY TO YOU.<br />V. INDEMNIFICATION</p>\n" +
                    "<p>You will release, indemnify, defend and hold harmless STYGIAN STORE, and<br />any of its contractors, agents, employees, officers, directors, shareholders,<br />affiliates and assigns from all liabilities, claims, damages, costs and expenses,<br />including reasonable attorneys' fees and expenses, of third parties relating to<br />or arising out of (1) these terms or the breach of your warranties,<br />representations and obligations under these terms; (2) the Website content or<br />your use of the Website content; (3) the Products or your use of the Products;<br />(4) any intellectual property or other proprietary right of any person or entity;<br />(5) your violation of any provision of this Agreement; or (6) any information<br />or data you supplied to the business.</p>\n" +
                    "<p><br /><strong>VI. PRIVACY</strong></p>\n" +
                    "<p>Stygian Store believes strongly in protecting user privacy and data protection.<br />Please refer to the Company&rsquo;s privacy policy mentioned on the website for<br />more details.</p>\n" +
                    "<p><strong>VI. AGREEMENT TO BE BOUND</strong></p>\n" +
                    "<p>By using this Website or ordering Products, you acknowledge that you have<br />read and agree to be bound by this Agreement and all terms and conditions<br />on this Website.</p>\n" +
                    "<p><br /><strong>VIII. GENERAL</strong></p>\n" +
                    "<p>Force Majeure: Stygian Store will not be deemed in default hereunder or held<br />responsible for any cessation, interruption or delay in the performance of its<br />obligations hereunder due to earthquake, flood, fire, storm, natural disaster,<br />act of God, war, terrorism, armed conflict, labor strike, lockout, or boycott.<br />Cessation of Operation: Stygian Store may at any time, in its sole discretion<br />and without advance notice to you, cease operation of the Website and<br />distribution of the Products.<br />Entire Agreement: These terms comprises the entire understanding between<br />you and the business and supersedes any prior terms pertaining to the subject<br />matter contained herein.<br />Effect of Waiver: The failure of Business to exercise or enforce any right or<br />provision of this Agreement will not constitute a waiver of such right or<br />provision. If any provision of this Agreement is found by a court of competent<br />jurisdiction to be invalid, the parties nevertheless agree that the court should<br />endeavor to give effect to the parties' intentions as reflected in the provision,<br />and the other provisions of this Agreement remain in full force and effect.<br />Governing Law &amp; Jurisdiction: This Website originates from the City of Bhopal<br />in the Indian State of Madhya Pradesh. These terms will be governed by the<br />laws of India. The courts of Bhopal Shall have jurisdiction in dealing with any<br />legal issue arising from these terms. By using this Website or ordering</p>\n" +
                    "<p>Products, you consent to the jurisdiction and venue of such courts in<br />connection with any action, suit, proceeding or claim arising under or by reason<br />of this Agreement.<br />Domestic Use: Stygian Store makes no representation that the Website or<br />Products are appropriate or available for use in locations outside India. Users<br />who access the Website from outside India do so at their own risk and initiative<br />and must bear all responsibility for compliance with any applicable local laws.<br />All applicable taxes shall have to borne by respective purchaser of the<br />products.</p>\n" +
                    "<p>&nbsp;</p>\n" +
                    "<p><strong><span style=\"font-size: 13pt;\">RETURN AND REFUND POLICY</span></strong></p>\n" +
                    "<p>Thank you for your purchase. We hope you are happy with your purchase. However,<br />if you are not completely satisfied with your purchase for any reason, you may return<br />it to us for a full refund or credit or an exchange only. Please see below for more<br />information on our return and refund policy.</p>\n" +
                    "<p><strong>RETURN POLICY</strong></p>\n" +
                    "<p>The following is the return policy as applicable to all items sold on<br />www.stygianstore.com.<br />1. In general, an item may be eligible for return within 7 days from the delivery date.<br />The product can be returned if it fulfils one or more of the following conditions:<br />o Was delivered in a physically damaged condition<br />o Has missing parts or accessories<br />o Is different from what was ordered<br />o Is different from its description on the product detail page on website</p>\n" +
                    "<p>Products marked as \"non-returnable\" on the product detail page cannot be<br />returned. Products which are imported or are specially requested by the customer<br />will be &ldquo;non- returnable&rdquo; unless the conditions mentioned in Clause 1 of the<br />return policy is applicable.<br />2. All items must be returned in their original condition, with price tags intact, user<br />manual, warranty cards, original accessories and in the original manufacturer&rsquo;s<br />box/packaging as delivered to you. We may reject the return pickup or reject the<br />returned item if the items are not returned according to the policy mentioned or<br />the item is not in a saleable condition.<br />3. If you wish to return an electronic device that stores any personal information,<br />please ensure that you have removed all such personal information from the</p>\n" +
                    "<p>device prior to returning. The Company or the marketplace shall not be liable in<br />any manner for any misuse or usage of such information.<br />4. In some cases, items may not be eligible for return, including cases of buyer's<br />remorse such as incorrect model or colour of product ordered or incorrect product<br />ordered.<br />5. Some of the goods available on the website may have a different return and refund<br />policy which shall be applicable only for the product where such policy is<br />specifically mentioned. In that case, this general policy will not be applicable to<br />such products or class or products.</p>\n" +
                    "<p><strong>Return Process</strong></p>\n" +
                    "<p>To return an item, initiate the return process by sending an email to the customer<br />service at __________________________ [email address] to confirm about the<br />goods to be returned. After receiving the confirmation of the return, place the item<br />securely in its original packaging and include your proof of Purchase /and the return<br />form provided (If any). A representative from the Shipping partner of the company or<br />seller will come and inspect the conditions on which the return can be executed and if<br />all the conditions are met he will take the item back and will issue the Goods Return<br />slip which shall be the proof that the goods has been returned and delivered to the<br />seller. In no case, the return shall be processed by Stygianstore.com, but we will only<br />be assisting in the whole process. The return shall be processed by the seller of the<br />product.</p>\n" +
                    "<p><strong>REFUND POLICY</strong></p>\n" +
                    "<p>In any case where a refund is required, the sellers need to authorise that refund.<br />Stygianstore.com can assist in facilitating refunds for you only when the seller notifies<br />us of the receipt of the item. Generally, the seller will process the refund within 7 days</p>\n" +
                    "<p>from the receipt of the product by the seller. Once the seller notifies us of the receipt<br />of the return item, the following timelines apply for the amount to be credited.</p>\n" +
                    "<p>Payment<br />Method</p>\n" +
                    "<p>Refund Method Refund Time-frame</p>\n" +
                    "<p>(After seller notifies Stygianstore.com<br />of receipt of return)</p>\n" +
                    "<p>Credit Card/<br />Debit Card</p>\n" +
                    "<p>Credit Card/<br />Debit Card</p>\n" +
                    "<p>3-5 Business Days</p>\n" +
                    "<p>Net Banking Net Banking<br />Account</p>\n" +
                    "<p>3-5 Business Days</p>\n" +
                    "<p>UPI UPI Linked Bank<br />Account</p>\n" +
                    "<p>2-4 Business days</p>\n" +
                    "<p>Pay on Delivery NEFT to Bank<br />Account</p>\n" +
                    "<p>3-5 Business Days</p>\n" +
                    "<p>In Rare circumstances, there may be delay in crediting of the refund amount even after<br />it being processed by the seller&rsquo;s bank. In such case, you may have to contact your</p>\n" +
                    "<p>bank for crediting the same to your account. The products which are categorized &ldquo;non-<br />returnable&rdquo;, no request for its refund or return or exchange will be taken unless the</p>\n" +
                    "<p>conditions mentioned in Clause 1 of the return policy is applicable.</p>\n" +
                    "<p>NOTE :- THE RETURN AND REFUND POLICY OF THE COMPANY IS SUBJECT TO<br />FURTHER CHANGE WITHOUT ANY FURTHER INTIMATION.</p>\n" +
                    "<p>.</p>"));
        }

    }
}
